#!/bin/bash

set -e

./testing/test-cli

sudo valgrind ./nhid 2> ./nhid.log &
nhid_ppid="$!"

sleep 5

echo export PS1=\"my_prompt \" \&\& source $PWD/shell/nhi.bash >> ~/.bashrc

./testing/expect-test || true

sed -i '$ d' ~/.bashrc

sudo pkill -2 -P "$nhid_ppid"

sleep 1
leaked_bytes="$(cat ./nhid.log | awk '$2 == "definitely" && $3 == "lost:"  { print $4; exit }')"
if [[ "$leaked_bytes" != "0" ]]; then
  echo Memory leak with "$leaked_bytes" bytes! 1>&2
  exit 1
fi

diff_result="$(diff ./testing/expected_output/fetch_after_expect-test <(./nhi fetch {-3}) || true)"
if [[ "$diff_result" != "" ]]; then
  echo The output of fetch is not expected! 1>&2
  exit 1
fi
