#!/bin/bash

diff_result="$(diff ./testing/expected_fetch <(./nhi fetch {-2}))"
if [[ "$diff_result" != "" ]]; then
  echo The output of fetch is not expected! 1>&2
  exit 1
fi

diff_result="$(diff ./testing/expected_log <(./nhi log))"
if [[ "$diff_result" != "" ]]; then
  echo The output of log is not expected! 1>&2
  exit 1
fi

diff_result="$(diff ./testing/expected_log_session <(./nhi log {-1}))"
if [[ "$diff_result" != "" ]]; then
  echo The output of log session is not expected! 1>&2
  exit 1
fi

./nhi rename {-2} session1
./nhi rename {-1} session2
diff_result="$(diff ./testing/expected_fetch <(./nhi fetch session1))"
if [[ "$diff_result" != "" ]]; then
  echo The output of fetch is not expected, rename failed! 1>&2
  exit 1
fi
