#!/bin/bash

testing_dir="$(dirname $0)"

touch $testing_dir/db
cat $testing_dir/original_db > $testing_dir/db

diff_result="$(diff $testing_dir/expected_output/fetch <($testing_dir/../nhi fetch {-2} -f))"
if [[ "$diff_result" != "" ]]; then
  echo The output of fetch is not expected! 1>&2
  exit 1
fi

diff_result="$(diff $testing_dir/expected_output/log <($testing_dir/../nhi log))"
if [[ "$diff_result" != "" ]]; then
  echo The output of log is not expected! 1>&2
  exit 1
fi

diff_result="$(diff $testing_dir/expected_output/log_session <($testing_dir/../nhi log-session {-1}))"
if [[ "$diff_result" != "" ]]; then
  echo The output of log session is not expected! 1>&2
  exit 1
fi

$testing_dir/../nhi rename {-2} session1
$testing_dir/../nhi rename {-1} session2
diff_result="$(diff $testing_dir/expected_output/fetch <($testing_dir/../nhi fetch session1 -f))"
if [[ "$diff_result" != "" ]]; then
  echo The output of fetch is not expected, rename failed! 1>&2

  $testing_dir/../nhi rename {-2} 16352740491
  $testing_dir/../nhi rename {-1} 16352740552
  exit 1
fi

$testing_dir/../nhi rename {-2} 16352740491
$testing_dir/../nhi rename {-1} 16352740552
